server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 5
    url:
      jdbc:log4jdbc:postgresql://211.170.81.110:3582/postgres
    username: postgres
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar
    call-setters-on-nulls: true
    auto-mapping-unknown-column-behavior: none
  type-aliases-package: co.kr.boot
